export const PROMPT_ENHANCERS = [
  { label: 'None', value: '' },
  { label: 'Strictly No Text', value: 'Strictly no text, no watermarks, no logos.' },
  { label: 'Unreal Engine 5', value: 'Unreal Engine 5 render, highly detailed, 8k resolution, cinematic lighting.' },
  { label: 'Anime Style', value: 'Anime style, Studio Ghibli, 2D animation, beautiful scenery, vibrant colors.' },
  { label: 'Horror / Dark', value: 'Horror style, dark, cinematic lighting, eerie, macabre, fog, ominous.' },
  { label: 'Cyberpunk', value: 'Cyberpunk style, neon lights, futuristic city, rainy night, high tech.' },
  { label: 'Watercolor', value: 'Watercolor painting, soft edges, pastel colors, artistic, fluid.' },
  { label: 'Photorealistic', value: 'Photorealistic, 35mm lens, f/1.8, extremely detailed, real life, ultra hd.' },
  { label: 'Retro 80s Synthwave', value: 'Retro 80s synthwave, grid background, neon pink and blue, sunset.' },
  { label: 'Minimalist Vector', value: 'Minimalist vector art, flat colors, clean lines, simple background.' },
  { label: 'Oil Painting', value: 'Classic oil painting, impasto brush strokes, museum quality, masterpiece.' },
  { label: '3D Pixar/Disney', value: '3D animation style, Pixar, Disney, cute, soft lighting, highly detailed.' },
  { label: 'Steampunk', value: 'Steampunk, brass, copper, gears, victorian era, steam-powered machinery.' },
  { label: 'Sci-Fi Space', value: 'Sci-Fi, deep space, stars, galaxies, futuristic spaceship, cosmic.' },
  { label: 'Fantasy Concept Art', value: 'Fantasy concept art, epic scale, magical, glowing elements, trending on ArtStation.' },
  { label: 'Vintage Photography', value: 'Vintage photography, sepia tone, film grain, light leaks, nostalgic.' },
  { label: 'Pop Art', value: 'Pop art, Andy Warhol style, bold colors, halftone dots, comic book style.' },
  { label: 'Low Poly 3D', value: 'Low poly 3D, geometric shapes, flat shading, isometric view.' },
  { label: 'Neon Noir', value: 'Neon noir, moody shadows, glowing neon signs, cinematic, mysterious.' },
  { label: 'Pencil Sketch', value: 'Detailed pencil sketch, crosshatching, graphite, artistic drawing.' },
  { label: 'Origami Paper Art', value: 'Origami paper art, folded paper, 3D papercraft, clean lighting.' },
  { label: 'Macro Photography', value: 'Macro photography, extreme close up, shallow depth of field, sharp focus.' },
  { label: 'Surrealism', value: 'Surrealism, Salvador Dali style, dreamlike, impossible physics, bizarre.' },
  { label: 'Gothic Architecture', value: 'Gothic architecture, dark academia, stained glass, gargoyles, ancient.' },
  { label: 'Vaporwave', value: 'Vaporwave aesthetic, greek statues, pastel pink and blue, early internet.' },
  { label: 'Claymation', value: 'Claymation style, stop motion, plasticine, textured, cute.' },
  { label: 'Stained Glass', value: 'Stained glass window art, vibrant colors, lead lines, illuminated from behind.' },
  { label: 'Double Exposure', value: 'Double exposure photography, overlapping silhouettes, nature and urban blend.' },
  { label: 'Ukiyo-e Woodblock', value: 'Ukiyo-e woodblock print, traditional Japanese art, flat colors, waves.' },
  { label: 'Glitch Art', value: 'Glitch art, chromatic aberration, data bending, vhs aesthetic.' },
  { label: 'Chibi Kawaii', value: 'Chibi style, kawaii, cute, big eyes, pastel colors.' },
  { label: 'Bioluminescent Nature', value: 'Bioluminescent, glowing plants, avatar pandora style, magical forest at night.' },
  { label: 'Isometric Room', value: 'Isometric room, cutaway view, miniature, detailed interior.' },
  { label: 'Line Art', value: 'Continuous line art, single stroke, minimalist, elegant.' },
  { label: 'Psychedelic', value: 'Psychedelic art, trippy, kaleidoscope colors, swirling patterns.' },
  { label: 'Noir Comic', value: 'Frank Miller style comic, high contrast black and white, harsh shadows, gritty.' },
  { label: 'Biomechanical', value: 'Biomechanical, H.R. Giger style, alien organic technology, dark, complex.' },
  { label: 'Voxel Art', value: 'Voxel art, 3D pixel art, minecraft style, blocky, colorful.' },
  { label: 'Tarot Card', value: 'Tarot card design, mystical, symbolic, ornate border, vintage.' },
  { label: 'Art Deco', value: 'Art deco, 1920s style, geometric patterns, gold and black, elegant.' },
  { label: 'Polaroid', value: 'Polaroid photo, instant camera, faded colors, white border, flash.' },
  { label: 'Street Art Graffiti', value: 'Street art, graffiti, spray paint, urban wall, vibrant, rebellious.' },
  { label: 'Chalkboard Art', value: 'Chalkboard drawing, white chalk on black, hand lettered, cafe menu style.' },
  { label: 'ASCII Art', value: 'ASCII art style, made of text characters, retro computer terminal.' },
  { label: 'Blueprint', value: 'Technical blueprint, cyanotype, white lines on blue background, architectural.' },
  { label: 'Tattoo Flash', value: 'Traditional tattoo flash art, bold outlines, limited color palette, vintage.' },
  { label: 'Mosaic', value: 'Mosaic art, small colored tiles, ancient roman style, intricate.' },
  { label: 'Infrared Photography', value: 'Infrared photography, aerochrome, red foliage, surreal landscape.' },
  { label: 'Silhouette', value: 'High contrast silhouette, backlit, dramatic sunset background.' },
  { label: 'Neon Wireframe', value: 'Neon wireframe, outrun, synthwave grid, glowing lines on black.' },
  { label: 'Bokeh', value: 'Heavy bokeh, out of focus background lights, dreamy, romantic.' },
  { label: 'Paper Quilling', value: 'Paper quilling art, rolled paper strips, 3D texture, intricate patterns.' },
];
